#!/bin/bash

## set temperature

TEMPERATURE=$1

if [ $TEMPERATURE == 0 ] 
then
	halcmd sets pid_en_mcode 0 
	halcmd sets temp_setpoint_mcode $TEMPERATURE
else
	halcmd sets pid_en_mcode 1 
	halcmd sets temp_setpoint_mcode $TEMPERATURE
fi

exit 0
